### ISSUE TITLE
enumerate at the inventory level causes 404

### ISSUE THREAD

**Issue by causten** [LRRoberts0122/openbmc#13]
/ org / openbmc / inventory
Tried to run the enumerate method....

 / org / openbmc / inventory
enumerate
Response

{
    "data": {
        "description": "org.openbmc.objectmapper.Error.NotFound: path or object not found: /org/openbmc/inventory/action"
    },
    "message": "404 Not Found",
    "status": "error"
}
Rerun
cURL

curl -X POST -H "Content-Type: application/json" http://9.3.23.24/org/openbmc/inventory/action/enumerate

**Comment by causten** [comment]
I think because the 'action' is not needed prepended to enumerate

**Comment by bradbishop** [comment]
I don't think I handle this.  There are two things to consider here:

GET: http://foo/org/openbmc/inventory/enumerate
POST: http://foo/org/openbmc/inventory/action/enumerate

So 'enumerate' is a rest keyword in the former case, but in the latter case it is a method on the inventory object.

I could probably make this work, but don't want to for a couple reasons:
- the enumerate method won't be used going forward - we'll use the standard dbus.ObjectManager interface.
- we probably don't want to encourage method names that are also rest keywords.

**Comment by causten** [comment]
I think we should open an issue in openbmc to have the interface removed.  I'll do that

**Comment by bradbishop** [comment]
@nkskjames will it impact anything if we get rid of the org.openbmc.ObjectEnumerate interface?  I've recently switched the rest server over to using freedesktop.ObjectManager.GetManagedObjects....

**Comment by causten** [comment]
I opened https://github.com/openbmc/openbmc/issues/218.  I'm closing this issue since the fix is not in this repo
